# -*- coding: utf-8 -*-
"""pandas.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-JkrP0_63bx3gZhG5BqU-eF5ztYUa0XS
"""

import pandas as pd
df=pd.read_csv("https://raw.githubusercontent.com/Premalatha-success/Datasets/main/CardioGoodFitness-1.csv")

df.sample()

df.head()

df.head(10)

df.tail(10)

df.sample(10)

df.shape

df.dtypes

df.info()

df.isnull().sum()

df.describe()

df.describe(include="all")

